export const ImageData=[
    {
        item_img:"/assets/Display_Items/Biryani.avif"
    },
    {
        item_img:"/assets/Display_Items/Pizza.avif"
    },
    {
        item_img:"/assets/Display_Items/Momos.avif"
    },
    {
        item_img:"/assets/Display_Items/Burger.avif"
    },
    {
        item_img:"/assets/Display_Items/Cakes.avif"
    },
    {
        item_img:"/assets/Display_Items/Dosa.avif"
    },
    {
        item_img:"/assets/Display_Items/Pakoda.avif"
    },
    {
        item_img:"/assets/Display_Items/Samosa.avif"
    },
    {
        item_img:"/assets/Display_Items/Shake.avif"
    },
    {
        item_img:"/assets/Display_Items/Pav_Bhaji.avif"
    },
    {
        item_img:"/assets/Display_Items/Shawarma.avif"
    },
    {
        item_img:"/assets/Display_Items/Punugulu.avif"
    },
    {
        item_img:"/assets/Display_Items/Salad.avif"
    },
    {
        item_img:"/assets/Display_Items/idli.avif"
    },
    {
        item_img:"/assets/Display_Items/pasta.avif"
    },
    {
        item_img:"/assets/Display_Items/cutlet.avif"
    },
    {
        item_img:"/assets/Display_Items/Pastry.avif"
    },
    {
        item_img:"/assets/Display_Items/Rolls.avif"
    },
    {
        item_img:"/assets/Display_Items/omlate.avif"
    },
    {
        item_img:"/assets/Display_Items/Desserts.avif"
    },
    {
        item_img:"/assets/Display_Items/Poori.avif"
    },
    {
        item_img:"/assets/Display_Items/South Indian.avif"
    },
    {
        item_img:"/assets/Display_Items/Parota.avif"
    },
    {
        item_img:"/assets/Display_Items/Chinese.avif"
    }
]
